export { default as Header } from "./Header";
export { default as Banner } from "./Banner";
export { default as WhoWeAre } from "./WhoWeAre";
export { default as Services } from "./Services";
export { default as Trainings } from "./Trainings";
export { default as Consultancy } from "./Consultancy";
export { default as Customers } from "./Customers";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
